import secrets

def crypt(data: str, key: list[int]):
    encrypted = ""

    for index, i in enumerate(data):
        encrypted += chr(ord(i) ^ key[index])

    return encrypted

if __name__ == "__main__":
    data = input("Text you want to encrypt: ")
    autogenerated = False
    while True:
        try:
            key = input("Your key. Type 0 to autogenerate: ")
            key = [int(i) for i in key.split()]
            if len(key) == 1 and key[0] == 0:
                autogenerated = True
            break
        except ValueError:
            pass

    if autogenerated:
        key = []
        for _ in range(len(data)):
            key.append(secrets.randbits(24))

    print("Your encrypted text:", crypt(data, key))
    if autogenerated:
        print("Your key:", " ".join([str(i) for i in key]))
